const genreTranslations: { [key: string]: string } = {
  'rock': 'Рок',
  'pop': 'Поп',
  'dance': 'Танцевальная',
  'electronic': 'Электроника',
  'hip hop': 'Хип-хоп',
  'hip-hop': 'Хип-хоп',
  'rap': 'Рэп',
  'jazz': 'Джаз',
  'classical': 'Классика',
  'metal': 'Метал',
  'alternative': 'Альтернатива',
  'indie': 'Инди',
  'blues': 'Блюз',
  'reggae': 'Регги',
  'folk': 'Фолк',
  'country': 'К��нтри',
  'soul': 'Соул',
  'funk': 'Фанк',
  'lounge': 'Лаунж',
  'techno': 'Техно',
  'trance': 'Транс',
  'house': 'Хаус',
  'drum and bass': 'Драм-н-бейс',
  'ambient': 'Эмбиент',
  'chillout': 'Чил-аут',
  'chill': 'Чил',
  'relax': 'Релакс',
  '80s': '80-е',
  '90s': '90-е',
  '00s': '00-е',
  '70s': '70-е',
  '60s': '60-е',
  'oldies': 'Ретро',
  'hits': 'Хиты',
  'top 40': 'Топ 40',
  'news': 'Новости',
  'talk': 'Разговорное',
  'sports': 'Спорт',
  'soundtracks': 'Саундтреки',
  'disco': 'Диско',
  'electro': 'Электро',
  'instrumental': 'Инструментальная',
  'rnb': 'R&B',
  'r&b': 'R&B',
  'world': 'Этника',
  'christian': 'Христианская',
  'gospel': 'Госпел',
  'adult contemporary': 'Современная взрослая',
  'classic rock': 'Классический рок',
  'hard rock': 'Тяжелый рок',
  'punk': 'Панк',
  'heavy metal': 'Хэви-метал',
  'death metal': 'Дэт-метал',
  'black metal': 'Блэк-метал',
  'progressive rock': 'Прогрессивный рок',
  'psychedelic': 'Психоделика',
  'synthpop': 'Синти-поп',
  'new wave': 'Новая волна',
  'idm': 'IDM',
  'dubstep': 'Дабстеп',
  'j-pop': 'J-Pop',
  'k-pop': 'K-Pop',
  'anime': 'Аниме',
  'video game music': 'Музыка из видеоигр',
  'latin': 'Латиноамериканская',
  'salsa': 'Сальса',
  'tango': 'Танго',
  'reggaeton': 'Регг��тон',
  'celtic': 'Кельтская',
  'opera': 'Опера',
  'baroque': 'Барокко',
  'romantic': 'Романтизм',
  'swing': 'Свинг',
  'big band': 'Биг-бэнд',
  'ska': 'Ска',
  'garage': 'Гараж',
  'jungle': 'Джангл',
  'hardcore': 'Хардкор',
  'gothic': 'Готика',
  'industrial': 'Индастриал',
  'ebm': 'EBM',
  'noise': 'Нойз',
  'experimental': 'Экспериментальная',
  'meditation': 'Медитация',
  'new age': 'Нью-эйдж',
  'kids': 'Детская',
  'christmas': 'Рождественская',
  'comedy': 'Комедия',
  'audiobooks': 'Аудиокниги',
  'poetry': 'Поэзия',
  'podcast': 'Подка��т',
  'downtempo': 'Даунтемпо',
  'trip hop': 'Трип-хоп',
  'chiptune': 'Чиптюн',
  'vaporwave': 'Вейпорвейв',
  'alternative rock': 'Альтернативный рок',
  'indie rock': 'Инди-рок',
  'electronic dance music': 'EDM',
  'edm': 'EDM',
  'synthwave': 'Синтвейв',
  'lo-fi': 'Лоу-фай',
  'chanson': 'Шансон',
  'voices': 'Голоса',
  'deep house': 'Дип-хаус',
  'progressive house': 'Прогрессив-хаус',
  'tech house': 'Тек-хаус',
  'minimal': 'Минимал',
  'dub': 'Даб',
  'psytrance': 'Пси-транс',
  'goa': 'Гоа-транс',
  'hardstyle': 'Хардстайл',
  'gabber': 'Габбер',
  'breakbeat': 'Брейкбит',
  'bass': 'Бейс',
  'soundtrack': 'Саундтрек',
  'ost': 'OST',
  'movie': 'Кино',
  'games': 'Игры',
  'retro': 'Ретро',
  'soviet': 'Советская',
  'russian': 'Русская',
  'ukrainian': '��краинская',
  'belarusian': 'Белорусская',
  'eurodance': 'Евр��денс',
  'europop': 'Европоп',
  'italo disco': 'Итало-диско',
  'post-punk': 'Пост-панк',
  'grunge': 'Гранж',
  'britpop': 'Брит-поп',
  'folk metal': 'Фолк-метал',
  'viking metal': 'Викинг-метал',
  'power metal': 'Пауэр-метал',
  'symphonic metal': 'Симфо-метал',
  'gothic metal': 'Готик-метал',
  'doom metal': 'Дум-метал',
  'thrash metal': 'Трэш-метал',
  'speed metal': 'С��ид-метал',
  'nu metal': 'Ню-метал',
  'metalcore': 'Металкор',
  'deathcore': 'Дэткор',
  'mathcore': 'Маткор',
  'grindcore': 'Грайндкор',
  'crust': 'Краст',
  'hardcore punk': 'Хардкор-панк',
  'oi!': 'Oi!',
  'emo': 'Эмо',
  'screamo': 'Скримо',
  'post-hardcore': 'Пост-хардкор',
  'shoegaze': 'Шугейз',
  'dream pop': 'Дрим-поп',
  'noise pop': 'Нойз-поп',
  'twee pop': 'Тви-поп',
  'indie pop': 'Инди-поп',
  'c86': 'C86',
  'post-rock': 'Пост-рок',
  'math rock': 'Мат-рок',
  'krautrock': 'Краут-рок',
  'space rock': 'Спейс-рок',
  'acid rock': 'Эйсид-рок',
  'blues rock': 'Блюз-рок',
  'rock and roll': 'Рок-н-ролл',
  'rockabilly': 'Рокабилли',
  'surf': 'Сёрф',
  'garage rock': 'Гаражный рок',
  'glam rock': 'Глэм-рок',
  'art rock': 'Арт-рок',
  'southern rock': 'Южный рок',
  'soft rock': 'Софт-рок',
  'pop rock': 'Поп-рок',
  'j-rock': 'J-Rock',
  'k-rock': 'K-Rock',
  'c-pop': 'C-Pop',
  'mandopop': 'Мандопоп',
  'cantopop': '��антопоп',
  'bossa nova': 'Босса-нова',
  'samba': 'Самба',
  'mpb': 'MPB',
  'cumbia': 'Кумбия',
  'bachata': 'Бачата',
  'merengue': 'Меренге',
  'mariachi': 'Мариачи',
  'ranchera': 'Ранчера',
  'flamenco': 'Фламенко',
  'fado': 'Ф��ду',
  'african': 'Африканская',
  'afrobeat': 'Афробит',
  'highlife': 'Хайлайф',
  'arabic': 'Арабская',
  'turkish': 'Турецкая',
  'indian': 'Индийская',
  'bollywood': 'Болли��уд',
  'bhangra': 'Бхангра',
  'persian': 'Персидская',
  'klezmer': 'Клезмер',
  'zydeco': 'Зайдеко',
  'cajun': 'Каджун',
  'bluegrass': 'Блюграсс',
  'americana': 'Американа',
  'singer-songwriter': 'Авторская песня',
  'gregorian chant': 'Григорианский хорал',
  'medieval': 'Средневековая',
  'renaissance': 'Ренессанс',
  'impressionist': 'Импрессиони��м',
  'modern': 'Модерн',
  'contemporary': 'Современная',
  'minimalism': 'Минимализм',
  'avant-garde': 'Авангард',
  'smooth jazz': 'Смус-джаз',
  'acid jazz': 'Эйсид-джаз',
  'cool jazz': 'Кул-джаз',
  'free jazz': 'Фри-джаз',
  'bebop': 'Бибоп',
  'dixieland': 'Диксиленд',
  'motown': 'Мотаун',
  'northern soul': 'Северный соул',
  'quiet storm': 'Quiet Storm',
  'neo soul': 'Нео-соул',
  'g-funk': 'G-Funk',
  'trap': 'Трэп',
  'drill': 'Дрилл',
  'boom bap': 'Бум-бэп',
  'conscious hip hop': 'Со��нательный хип-хоп',
  'gangsta rap': 'Гангста-рэп',
  'horrorcore': 'Хоррорко́р',
  'turntablism': 'Тёрнтейблизм',
  'freestyle': 'Фристайл',
  'miami bass': 'Май��ми-бейс',
  'crunk': 'Кранк',
  'hyphy': 'Хайфи',
  'nerdcore': 'Нердкор',
  'glitch': 'Глитч',
  'glitch hop': 'Глитч-хоп',
  'future bass': 'Фьюче-бейс',
  'hardbass': 'Хардбасс',
  'eurobeat': 'Евро��ит',
  'happy hardcore': 'Хэппи-хардкор',
  'uk garage': 'UK Garage',
  '2-step': '2-step',
  'speed garage': 'Спид-гэридж',
  'bassline': 'Бейслайн',
  'grime': 'Грайм',
  'wonky': 'Вонки',
  'future garage': 'Фьюче-гэридж',
  'post-dubstep': 'Пост-дабстеп',
  'brostep': 'Бростеп',
  'riddim': 'Риддим',
  'neurofunk': 'Нейрофанк',
  'liquid funk': 'Ликвид-фанк',
  'jump-up': 'Джамп-ап',
  'darkstep': 'Даркстеп',
  'techstep': 'Текстеп',
  'hardstep': 'Хардстеп',
  'ragga jungle': 'Рагга-джангл',
  'intelligent dance music': 'IDM',
  'braindance': '��рейнданс',
  'acid techno': 'Эйсид-техно',
  'detroit techno': 'Детройт-техно',
  'dub techno': 'Даб-техно',
  'hardtek': 'Хардтек',
  'schranz': 'Шранц',
  'industrial hardcore': 'Индастриал-хардкор',
  'speedcore': 'Спидкор',
  'terrorcore': 'Террорко́р',
  'frenchcore': 'Френчкор',
  'progressive trance': 'Прогрессив-транс',
  'uplifting trance': 'Ап��ифтинг-транс',
  'tech trance': 'Тек-транс',
  'vocal trance': 'Вокальный транс',
  'hard trance': 'Хард-транс',
  'acid trance': 'Эйсид-транс',
  'dream trance': 'Дрим-транс',
  'balearic': 'Бал��арик',
  'tribal house': 'Трайбл-хаус',
  'funky house': '��анки-хаус',
  'electro house': 'Электро-хаус',
  'dutch house': 'Датч-хаус',
  'big room': 'Биг-рум',
  'moombahton': 'Мумбатон',
  'tropical house': 'Тропикал-хаус',
  'witch house': 'Витч-хаус',
  'seapunk': 'Сипанк',
  'chillwave': 'Чиллвейв',
  'hypnagogic pop': 'Гипнагоджик-поп',
  'lofi hip hop': 'Лоу-фай хип-хоп',
  'phonk': 'Фонк',
  'cloud rap': '��лауд-рэп',
  'emo rap': 'Эмо-рэп',
  'mumble rap': 'Мамбл-рэп',
  'plunderphonics': 'Пла́ндерфоника',
  'mashup': 'Мэшап',
  'remix': 'Ремикс',
  'cover': 'Кавер',
  'live': 'Лайв',
  'acoustic': 'Акустика',
  'unplugged': 'Анплагд',
  'karaoke': 'Караоке',
  'demo': 'Демо',
  'bootleg': 'Бут��ег',
  'field recordings': 'Полевые записи',
  'nature': 'Природ��',
  'weather': 'Погода',
  'education': 'Образование',
  'science': 'Наука',
  'technology': 'Технологии',
  'history': 'История',
  'philosophy': 'Философия',
  'psychology': 'Психология',
  'politics': 'Политика',
  'business': 'Бизнес',
  'finance': 'Финансы',
  'health': 'З��оровье',
  'fitness': 'Фитнес',
  'spirituality': 'Духовность',
  'religion': 'Религия',
  'culture': 'Культура',
  'society': '��бщество',
  'travel': 'Путешествия',
  'food': 'Еда',
  'gaming': 'Г��йминг',
  'movies': 'Кино',
  'television': 'Телевидение',
  'books': 'Книги',
  'art': 'Искусство',
  'design': 'Дизайн',
  'fashion': 'Мода',
  'automotive': 'Автомобил��',
  'aviation': 'Авиация',
  'military': 'Военное',
  'police': 'Поли��ия',
  'fire': 'Пожарные',
  'scanner': 'Сканер',
  'ham radio': 'Радиолюбители',
  'shortwave': 'Короткие волны',
  'pirate radio': 'Пиратское радио',
  'campus': 'Студенческое',
  'community': 'Местное',
  'public radio': 'Общественное радио',
  'commercial': 'Ком��ерческое',
  'independent': 'Независимое',
  'internet': 'Интернет',
  'satellite': 'Спутниковое',
  'am': 'AM',
  'fm': 'FM',
  'dab': 'DAB',
  'hd radio': 'HD Radio',
};
const countryTranslations: { [key:string]: string } = {
  'Russia': 'Россия',
  'Russian Federation': 'Россия',
  'The Russian Federation': 'Россия',
  'Ukraine': 'Украина',
  'Belarus': 'Беларусь',
  'Kazakhstan': 'Казахстан',
  'United States': 'США',
  'The United States Of America': 'США',
  'USA': 'США',
  'United Kingdom': 'Велико��ритания',
  'UK': 'Великобритания',
  'Germany': 'Германия',
  'France': 'Франция',
  'Italy': 'Италия',
  'Spain': 'Испания',
  'Poland': 'Польша',
  'Netherlands': 'Нидерланды',
  'Canada': 'Канада',
  'Japan': 'Япония',
  'China': 'Китай',
  'Brazil': 'Бразилия',
  'India': 'Индия',
  'Australia': 'Австралия',
  'Argentina': 'Аргентина',
  'Mexico': 'Мексика',
  'Sweden': 'Швеция',
  'Norway': 'Н��рвегия',
  'Finland': 'Финляндия',
  'Denmark': 'Дания',
  'Switzerland': 'Швейцария',
  'Austria': 'Австрия',
  'Belgium': 'Бельгия',
  'Portugal': 'Португалия',
  'Greece': 'Греция',
  'Turkey': 'Турция',
  'Ireland': 'Ирландия',
  'Czech Republic': 'Ч��хия',
  'Hungary': 'Венгрия',
  'Romania': 'Румыния',
  'Bulgaria': 'Болгария',
  'Serbia': 'Сербия',
  'Croatia': 'Хорв��тия',
  'Slovenia': 'Словения',
  'Slovakia': 'Словакия',
  'Estonia': 'Эстония',
  'Latvia': 'Латвия',
  'Lithuania': 'Литва',
  'Israel': 'Израиль',
  'South Korea': 'Южная Корея',
  'Armenia': 'Армения',
  'Azerbaijan': 'Азербайджан',
  'Georgia': 'Грузия',
  'Moldova': 'М��лдова',
  'Uzbekistan': 'Узбекистан',
  'Kyrgyzstan': '��иргизия',
  'Tajikistan': 'Таджикистан',
  'Turkmenistan': 'Туркменистан',
  'Peru': 'Перу',
  'Chile': 'Чили',
  'Colombia': 'Колумбия',
  'South Africa': 'Южная Африка',
  'Egypt': 'Египет',
  'Nigeria': 'Нигерия',
  'Thailand': 'Таиланд',
  'Vietnam': 'Вьетнам',
  'Indonesia': 'Индонезия',
  'Malaysia': 'Малайзия',
  'Philippines': 'Филиппины',
  'New Zealand': 'Новая Зеландия',
  'United Arab Emirates': 'ОАЭ',
  'UAE': 'ОАЭ',
  'Saudi Arabia': 'Саудовская Аравия',
  'Afghanistan': 'Афганистан',
  'Albania': 'Албания',
  'Algeria': 'Алжир',
  'Andorra': 'Андорра',
  'Angola': 'Ангола',
  'Antigua and Barbuda': 'Антигуа и Барбуда',
  'Bahamas': 'Багамы',
  'Bahrain': 'Бахрейн',
  'Bangladesh': 'Бангладеш',
  'Barbados': 'Барбадос',
  'Belize': 'Белиз',
  'Benin': 'Бенин',
  'Bhutan': 'Бутан',
  'Bolivia': 'Бол��вия',
  'Bosnia and Herzegovina': 'Бос��ия и Герцеговина',
  'Botswana': 'Ботсвана',
  'Brunei Darussalam': 'Бруней',
  'Burkina Faso': 'Буркина-Фасо',
  'Burundi': 'Бурун��и',
  'Cambodia': 'Камбоджа',
  'Cameroon': 'Камерун',
  'Cape Verde': 'Кабо-Верде',
  'Central African Republic': 'Центральноафриканская Республика',
  'Chad': 'Чад',
  'Comoros': 'Коморы',
  'Congo': 'Конго',
  'Costa Rica': 'Коста-Рика',
  "Cote D'Ivoire": 'Кот-д’Ивуар',
  'Cuba': 'Куба',
  'Cyprus': 'Кипр',
  'Djibouti': 'Джибути',
  'Dominica': 'Доминика',
  'Dominican Republic': 'Доминиканская Республика',
  'Ecuador': 'Экв��дор',
  'El Salvador': 'Сальвадор',
  'Equatorial Guinea': 'Экваториальная Гвинея',
  'Eritrea': 'Эритрея',
  'Ethiopia': 'Эфиопия',
  'Fiji': 'Фиджи',
  'Gabon': 'Габон',
  'Gambia': 'Гамбия',
  'Ghana': 'Гана',
  'Grenada': 'Гренада',
  'Guatemala': 'Г��атемала',
  'Guinea': 'Гвинея',
  'Guinea-Bissau': 'Гвинея-Бисау',
  'Guyana': 'Гайана',
  'Haiti': 'Гаити',
  'Honduras': 'Гондурас',
  'Iceland': 'Исландия',
  'Iran': 'Иран',
  'Iraq': 'Ирак',
  'Jamaica': 'Ямайка',
  'Jordan': 'Иордания',
  'Kenya': 'К��ния',
  'Kiribati': 'Кирибати',
  'Kuwait': 'Кувей��',
  'Laos': 'Лаос',
  'Lebanon': 'Ливан',
  'Lesotho': 'Лесото',
  'Liberia': 'Либерия',
  'Libya': 'Ливия',
  'Liechtenstein': 'Лихтенштейн',
  'Luxembourg': 'Люксембург',
  'Macedonia': 'Македония',
  'Madagascar': 'Мадагаскар',
  'Malawi': 'Малави',
  'Maldives': 'Мальди��ы',
  'Mali': 'Мали',
  'Malta': 'Мальта',
  'Marshall Islands': 'Маршалловы Острова',
  'Mauritania': 'Мавритания',
  'Mauritius': 'Маврикий',
  'Micronesia': 'Микронезия',
  'Monaco': 'Монако',
  'Mongolia': 'Монголия',
  'Montenegro': 'Черногория',
  'Morocco': 'Марокко',
  'Mozambique': 'Мозамбик',
  'Myanmar': 'Мьянма',
  'Namibia': 'Намибия',
  'Nauru': 'Науру',
  'Nepal': 'Непал',
  'Nicaragua': 'Никарагуа',
  'Niger': 'Нигер',
  'North Korea': 'Северная Корея',
  'Oman': 'Оман',
  'Pakistan': 'Пакистан',
  'Palau': 'Палау',
  'Panama': 'Панама',
  'Papua New Guinea': 'Папуа — Новая Гвинея',
  'Paraguay': 'Парагва��',
  'Qatar': 'Катар',
  'Rwanda': 'Руанда',
  'Saint Kitts and Nevis': 'Сент-Китс и Невис',
  'Saint Lucia': 'Сент-Люсия',
  'Saint Vincent and the Grenadines': 'Сент-Винсент и Гренадины',
  'Samoa': 'Самоа',
  'San Marino': 'Сан-Марино',
  'Sao Tome and Principe': 'Сан-Том�� и Принсипи',
  'Senegal': 'Сенегал',
  'Seychelles': 'Сейшелы',
  'Sierra Leone': 'Сьерра-Леоне',
  'Singapore': 'Сингапур',
  'Solomon Islands': 'Соломоновы Острова',
  'Somalia': 'Сомали',
  'Sri Lanka': 'Шри-Ланка',
  'Sudan': 'Судан',
  'Suriname': 'Суринам',
  'Swaziland': 'Свазиленд',
  'Syria': 'Сирия',
  'Taiwan': 'Тайвань',
  'Tanzania': 'Танзания',
  'Timor-Leste': 'Восточный Тимор',
  'Togo': 'Того',
  'Tonga': 'Тонга',
  'Trinidad and Tobago': 'Тринидад и Тобаго',
  'Tunisia': 'Тун��с',
  'Tuvalu': 'Тувалу',
  'Uganda': 'Уганда',
  'Uruguay': '��ругвай',
  'Vanuatu': 'Вануату',
  'Vatican City': 'Ватикан',
  'Venezuela': 'Венесуэла',
  'Yemen': 'Йемен',
  'Zambia': 'Замбия',
  'Zimbabwe': 'Зимбаб��е',
  'Worldwide': 'Всемирный',
  'International': 'Международный',
};
const capitalize = (s: string) => {
  if (typeof s !== 'string' || !s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
};
export function translateGenre(genre: string): string {
  if (!genre) return '';
  const lowerGenre = genre.toLowerCase();
  return genreTranslations[lowerGenre] ? capitalize(genreTranslations[lowerGenre]) : capitalize(genre);
}
export function translateCountry(country: string): string {
  if (!country) return '';
  return countryTranslations[country] || country;
}