const genreTranslations: { [key: string]: string } = {
  'rock': 'Рок',
  'pop': 'Поп',
  'dance': 'Танцевальная',
  'electronic': 'Электроника',
  'hip hop': 'Хип-хоп',
  'hip-hop': 'Хип-хоп',
  'rap': 'Рэп',
  'jazz': 'Джаз',
  'classical': 'Классика',
  'metal': 'Метал',
  'alternative': 'Альтернатива',
  'indie': 'Инди',
  'blues': 'Блюз',
  'reggae': 'Регги',
  'folk': 'Фолк',
  'country': 'Кантри',
  'soul': 'Соул',
  'funk': 'Фанк',
  'lounge': 'Лаунж',
  'techno': 'Техно',
  'trance': 'Транс',
  'house': 'Хаус',
  'drum and bass': 'Драм-н-бейс',
  'ambient': 'Эмбиент',
  'chillout': 'Чил-аут',
  'chill': 'Чил',
  'relax': 'Релакс',
  '80s': '80-е',
  '90s': '90-е',
  '00s': '00-е',
  '70s': '70-е',
  '60s': '60-е',
  'oldies': 'Ретро',
  'hits': 'Хиты',
  'top 40': 'Топ 40',
  'news': 'Новости',
  'talk': 'Разговорное',
  'sports': 'Спорт',
  'soundtracks': 'Саундтреки',
  'disco': 'Диско',
  'electro': 'Электро',
  'instrumental': 'Инструментальная',
  'rnb': 'R&B',
  'r&b': 'R&B',
  'world': 'Этника',
  'christian': 'Христианская',
  'gospel': 'Госпел',
  'adult contemporary': 'Современная взрослая',
  'classic rock': 'Классический рок',
  'hard rock': 'Тяжелый рок',
  'punk': 'Панк',
  'heavy metal': 'Хэви-метал',
  'death metal': 'Дэт-метал',
  'black metal': 'Блэк-метал',
  'progressive rock': 'Прогрессивный рок',
  'psychedelic': 'Психоделика',
  'synthpop': 'Синти-поп',
  'new wave': 'Новая волна',
  'idm': 'IDM',
  'dubstep': 'Дабстеп',
  'j-pop': 'J-Pop',
  'k-pop': 'K-Pop',
  'anime': 'Аниме',
  'video game music': 'Музыка из видеоигр',
  'latin': 'Латиноамериканская',
  'salsa': 'Сальса',
  'tango': 'Танго',
  'flamenco': 'Фламенко',
  'reggaeton': 'Реггетон',
  'celtic': 'Кельтская',
  'opera': 'Опера',
  'baroque': 'Барокко',
  'romantic': 'Романтизм',
  'swing': 'Свинг',
  'big band': 'Биг-бэнд',
  'ska': 'Ска',
  'garage': 'Гараж',
  'jungle': 'Джангл',
  'hardcore': 'Хардкор',
  'gothic': 'Готика',
  'industrial': 'Индастриал',
  'ebm': 'EBM',
  'noise': 'Нойз',
  'experimental': 'Экспериментальная',
  'meditation': 'Медитация',
  'new age': 'Нью-эйдж',
  'kids': 'Детская',
  'christmas': 'Рождественская',
  'comedy': 'Комедия',
  'audiobooks': 'Аудиокниги',
  'poetry': 'Поэзия',
  'podcast': 'Подкаст',
  'downtempo': 'Даунтемпо',
  'trip hop': 'Трип-хоп',
  'chiptune': 'Чиптюн',
  'vaporwave': 'Вейпорвейв',
  'alternative rock': 'Альтернативный рок',
  'indie rock': 'Инди-рок',
  'electronic dance music': 'EDM',
  'edm': 'EDM',
  'synthwave': 'Синтвейв',
  'lo-fi': 'Лоу-фай',
  'chanson': 'Шансон',
  'voices': 'Голоса',
};
const countryTranslations: { [key:string]: string } = {
  'Russia': 'Россия',
  'Russian Federation': 'Россия',
  'The Russian Federation': 'Россия',
  'Ukraine': 'Украина',
  'Belarus': 'Беларусь',
  'Kazakhstan': 'Казахстан',
  'United States': 'США',
  'The United States Of America': 'США',
  'USA': 'США',
  'United Kingdom': 'Великобритания',
  'UK': 'Великобритания',
  'Germany': 'Германия',
  'France': 'Франция',
  'Italy': 'Италия',
  'Spain': 'Испания',
  'Poland': 'Польша',
  'Netherlands': 'Нидерланды',
  'Canada': 'Канада',
  'Japan': 'Япония',
  'China': 'Китай',
  'Brazil': 'Бразилия',
  'India': 'Индия',
  'Australia': 'Австралия',
  'Argentina': 'Аргентина',
  'Mexico': 'Мексика',
  'Sweden': 'Швеция',
  'Norway': 'Норвегия',
  'Finland': 'Финляндия',
  'Denmark': 'Дания',
  'Switzerland': 'Швейцария',
  'Austria': 'Австрия',
  'Belgium': 'Бельгия',
  'Portugal': 'Португалия',
  'Greece': 'Греция',
  'Turkey': 'Турция',
  'Ireland': 'Ирландия',
  'Czech Republic': 'Чехия',
  'Hungary': 'Венгрия',
  'Romania': 'Румыния',
  'Bulgaria': 'Болгария',
  'Serbia': 'Сербия',
  'Croatia': 'Хорватия',
  'Slovenia': 'Словения',
  'Slovakia': 'Словакия',
  'Estonia': 'Эстония',
  'Latvia': 'Латвия',
  'Lithuania': 'Литва',
  'Israel': 'Израиль',
  'South Korea': 'Южная Корея',
  'Armenia': 'Армения',
  'Azerbaijan': 'Азербайджан',
  'Georgia': 'Грузия',
  'Moldova': 'Молдова',
  'Uzbekistan': 'Узбекистан',
  'Kyrgyzstan': 'Киргизия',
  'Tajikistan': 'Таджикистан',
  'Turkmenistan': 'Туркменистан',
  'Peru': 'Перу',
  'Chile': 'Чили',
  'Colombia': 'Колумбия',
  'South Africa': 'Южная Африка',
  'Egypt': 'Египет',
  'Nigeria': 'Нигерия',
  'Thailand': 'Таиланд',
  'Vietnam': 'Вьетнам',
  'Indonesia': 'Индонезия',
  'Malaysia': 'Малайзия',
  'Philippines': 'Филиппины',
  'New Zealand': 'Новая Зеландия',
  'United Arab Emirates': 'ОАЭ',
  'UAE': 'ОАЭ',
  'Saudi Arabia': 'Саудовская Аравия',
};
const capitalize = (s: string) => {
  if (typeof s !== 'string' || !s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
};
export function translateGenre(genre: string): string {
  if (!genre) return '';
  const lowerGenre = genre.toLowerCase();
  return genreTranslations[lowerGenre] ? capitalize(genreTranslations[lowerGenre]) : capitalize(genre);
}
export function translateCountry(country: string): string {
  if (!country) return '';
  return countryTranslations[country] || country;
}